### ISSUE TITLE
v2.6 doesn't play nice with Enumerize gem anymore

### ISSUE THREAD

**Issue by jmuheim** [amerine/acts_as_tree#57]
I have this model:

class SuccessCriterion < ActiveRecord::Base
  extend Enumerize
  extend ActsAsTree::TreeWalker

  enumerize :level, in: [:a, :aa, :aaa]

  acts_as_tree order: :position, dependent: :restrict_with_error
  acts_as_list scope: [:parent_id]
end
```

After upgrading from v2.5.1 to v2.6, I get this error when calling`success_criterion.level_text`:

    undefined method `text' for 0:Fixnum

Any idea where's the problem?

**Comment by felixbuenemann** [comment]
ActsAsTree defines it's own method called `level` which is likely clashing with your enumerize attribute of the same name. The easiest fix would probably be to rename your `level` column to something else.

**Comment by felixbuenemann** [comment]
If you want to keep your method as is, you could create a monkey patch in an initializer like `config/initializers/acts_as_tree_remove_level.rb` with the following content:

```ruby
module ActsAsTree
  module InstanceMethods
    undef tree
  end
end
```

**Comment by jmuheim** [comment]
Good to know. Thank you!

**Comment by jmuheim** [comment]
FYI: The problem didn't occur to me anymore with the newest version.

Thank you.
